
// global actions
export const GLOBAL_CHANGE_LOCALE = 'GLOBAL_CHANGE_LOCALE';
export const GLOBAL_SET_TITLE = 'GLOBAL_SET_TITLE';


// user actions
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_CHANGE_PROFILE_SUCCESS = 'USER_CHANGE_PROFILE_SUCCESS';
export const USER_GET_USER_SUCCESS = 'USER_GET_USER_SUCCESS';
export const USER_UPDATE_USER_SUCCESS = 'USER_UPDATE_USER_SUCCESS';
export const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS';

